export const leads = [
  {
      "number": "95724",
      "customer": "Alex Bibishev",
      "status": "ready",
      "actual": "1000",
      "total": "10406.5",
      "type": "company",
      "create_date": "Aug 26, 2020",
      "close_date": "Aug 26, 2020",
      "country": "Ukraine",
  },
  {
      "number": "95725",
      "customer": "Alex Bibishev",
      "status": "processing",
      "actual": "1000",
      "total": "10406.5",
      "type": "company",
      "create_date": "Aug 27, 2020",
      "close_date": "Aug 27, 2020",
      "country": "Ukraine",
  },
  {
    "number": "95726",
    "customer": "Kirill Bibishev",
    "status": "processing",
    "actual": "1000",
    "total": "10406.5",
    "type": "company",
    "create_date": "February 22, 2021",
    "close_date": "February 22, 2021",
    "country": "Ukraine",
  },
  {
    "number": "95727",
    "customer": "Tamara Bibisheva",
    "status": "decline",
    "actual": "2000",
    "total": "10406.5",
    "type": "company",
    "create_date": "Aug 26, 2021",
    "close_date": "Aug 26, 2021",
    "country": "Ukraine",
  },
    {
        "number": "95728",
        "customer": "Masha Chernova",
        "status": "decline",
        "actual": "7800",
        "total": "10406.5",
        "type": "product",
        "create_date": "Feb 18, 2021",
        "close_date": "Feb 18, 2021",
        "country": "Poland",
    },
]